// Generated by LiveScript 1.4.0
(function(){
  var request, domino, URL, ref$, renderAll, renderTweet, main;
  request = require('request');
  domino = require('domino');
  URL = require('url');
  ref$ = require('./shared'), renderAll = ref$.renderAll, renderTweet = ref$.renderTweet;
  main = function(){
    var url, domain;
    url = process.argv[2];
    domain = URL.parse(url).host;
    return request(url, function(error, response, body){
      var win;
      if (error) {
        console.error(error);
        process.exit(1);
      }
      win = domino.createWindow(body);
      switch (domain) {
      case 'twitter.com':
        return renderTweet(win);
      default:
        return renderAll(win);
      }
    });
  };
  main();
}).call(this);
