// Generated by LiveScript 1.5.0
(function(){
  var request, domino, URL, ref$, renderSummary, renderTweet, fixEncoding, main;
  request = require('request');
  domino = require('domino');
  URL = require('url');
  ref$ = require('./shared'), renderSummary = ref$.renderSummary, renderTweet = ref$.renderTweet, fixEncoding = ref$.fixEncoding;
  main = function(){
    var url, domain;
    url = process.argv[2];
    domain = URL.parse(url).host;
    return request({
      url: url,
      encoding: null
    }, function(error, response, body){
      var win;
      if (error) {
        console.error(error);
        process.exit(1);
      }
      body = fixEncoding(response, body);
      win = domino.createWindow(body);
      win.url = url;
      return renderSummary(win, domain);
    });
  };
  main();
}).call(this);
