// Generated by LiveScript 1.5.0
(function(){
  var request, supported, extractJson, extractHtml, extract, out$ = typeof exports != 'undefined' && exports || this;
  request = require('request');
  out$.supported = supported = function(win){
    var ref$, providers, i$, len$, provider, results$ = [];
    if ((ref$ = win.document.querySelector("link[type=\"application/json+oembed\"]")) != null && ref$.attributes.href) {
      return true;
    }
    providers = require("../data/oembed-providers");
    for (i$ = 0, len$ = providers.length; i$ < len$; ++i$) {
      provider = providers[i$];
      results$.push('ok');
    }
    return results$;
  };
  out$.extractJson = extractJson = function(win, cb){};
  out$.extractHtml = extractHtml = function(win, cb, fail){
    return extract(win, cb, fail);
  };
  extract = function(win, cb, fail){
    var oembedUrl, ref$, width;
    oembedUrl = (ref$ = win.document.querySelector("link[type=\"application/json+oembed\"]")) != null ? ref$.attributes.href.value : void 8;
    if (!oembedUrl) {
      return fail();
    }
    width = process.env.OEMBED_WIDTH || 500;
    oembedUrl += "&maxwidth=" + width;
    return request(oembedUrl, function(error, response, body){
      var data;
      data = JSON.parse(body);
      if (data.type === 'image') {
        data.html = "<img src=\"" + data.url + "\">";
      }
      return cb(data);
    });
  };
}).call(this);
