// Generated by LiveScript 1.5.0
/*
export supported = (win) ->
  # if there's a title assume it's ok
  !!(win.document.query-selector("meta[property=\"twitter:title\"]") or
    win.document.query-selector("meta[property=\"og:title\"]") ]
*/
(function(){
  var extractHtml, extractJson, extract, out$ = typeof exports != 'undefined' && exports || this;
  out$.extractHtml = extractHtml = function(win, cb){
    return extract(win, cb, function(json){
      var out;
      out = "<div><h1>" + json.title + "</h1>";
      if (json.image) {
        out += "<img src=\"" + json.image + "\">";
      }
      if (json.description) {
        out += "<div>" + json.description + "</div>";
      }
      out += "</div>";
      return out;
    });
  };
  out$.extractJson = extractJson = function(win, cb){
    return extract(win, cb, function(){});
  };
  extract = function(win, cb, formatter){
    var coreProp, prop, getProp, res;
    coreProp = function(win, p){
      return function(it){
        var ref$;
        return (ref$ = it[0]) != null ? ref$.attributes.content.value : void 8;
      }(
      filter(function(it){
        var ref$, ref1$;
        return ((ref$ = it.attributes.content) != null ? (ref1$ = ref$.value) != null ? ref1$.length : void 8 : void 8) > 0;
      })(
      win.document.querySelectorAll("meta[property=\"" + p + "\"]")));
    };
    prop = function(win, p){
      return coreProp(win, "twitter:" + p) || coreProp(win, "og:" + p);
    };
    getProp = function(it){
      return prop(win, it);
    };
    res = {};
    res.title = getProp('title');
    if (!res.title) {
      return null;
    }
    res.description = getProp('description');
    res.image = getProp('image');
    res = formatter(res);
    return cb(res);
  };
}).call(this);
