// Generated by LiveScript 1.4.0
(function(){
  var request, domino, URL, getPrinter, renderAll, renderSummary, renderTweet, out$ = typeof exports != 'undefined' && exports || this;
  request = require('request');
  domino = require('domino');
  URL = require('url');
  out$.getPrinter = getPrinter = function(opts){
    if (opts[0] === '-r') {
      return function(it){
        return console.log(it.innerHTML);
      };
    }
    return function(it){
      return console.log(it.textContent.trim());
    };
  };
  out$.renderAll = renderAll = function(win){
    var nodes, i$, len$, node, results$ = [];
    nodes = win.document.querySelectorAll("H1, H3, P, IMG, LI");
    for (i$ = 0, len$ = nodes.length; i$ < len$; ++i$) {
      node = nodes[i$];
      results$.push(console.log((fn$())));
    }
    return results$;
    function fn$(){
      switch (node.tagName) {
      case 'H1':
        return '# ' + node.textContent + "\n";
      case 'H3':
        return '### ' + node.textContent + "\n";
      case 'IMG':
        return node.src + "\n";
      case 'LI':
        return node.textContent;
      case 'P':
        return node.textContent + "\n";
      default:
        return node.textContent;
      }
    }
  };
  out$.renderSummary = renderSummary = function(win){
    var nodes, imgs, ps;
    console.log(win.document.title);
    nodes = win.document.querySelectorAll("H1, P, IMG");
    while (nodes[0] && nodes[0].tagName !== 'H1') {
      nodes.shift();
    }
    if (nodes.length === 0) {
      return;
    }
    nodes.shift();
    if (nodes.length === 0) {
      return;
    }
    imgs = nodes.filter(function(it){
      return it.tagName === 'IMG';
    });
    if (imgs.length > 0) {
      console.log(imgs[0].src);
    }
    ps = nodes.filter(function(it){
      return it.tagName === 'P';
    });
    if (ps.length > 0) {
      return console.log(ps[0].textContent);
    }
  };
  out$.renderTweet = renderTweet = function(win){
    var ref$;
    return console.log((ref$ = win.document.querySelector('p.TweetTextSize')) != null ? ref$.textContent : void 8);
  };
}).call(this);
